### **Pandas**


In [ ]:
import pandas as pd

In [ ]:
dataset = {
    'cars':["Toyota","Porsche","Ferrari"],
    'passings':[3,7,2]
}
var1 = pd.DataFrame(dataset)
print(var1)

      cars  passings
0   Toyota         3
1  Porsche         7
2  Ferrari         2


In [ ]:
a = [1,7,2]
var2 = pd.Series(a)
print(var2)

0    1
1    7
2    2
dtype: int64


In [ ]:
a = [1,7,2]
var3 = pd.Series(a,index=["x","y","z"])
print(var3)
print(var3["y"])

x    1
y    7
z    2
dtype: int64
7


# Pandas and Numpy

In [ ]:
import numpy as np

In [ ]:
ser = pd.Series()
print(ser)

Series([], dtype: float64)


<ipython-input-15-e6bad121ff5c>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser = pd.Series()


In [ ]:
data = np.array(['p','y','t','h','o','n'])
ser = pd.Series(data)
print(ser)

0    p
1    y
2    t
3    h
4    o
5    n
dtype: object


In [ ]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
lst = ['python','r','data','science','sentiment','nlp']
df1 = pd.DataFrame(lst)
print(df1)

           0
0     python
1          r
2       data
3    science
4  sentiment
5        nlp


In [ ]:
print(var2[0])

1


In [ ]:
Data =[1, 3, 4, 5, 6, 2, 9]
s = pd.Series(Data)
Index =['a', 'b', 'c', 'd', 'e', 'f', 'g']
si = pd.Series(Data, Index)
print(si)

a    1
b    3
c    4
d    5
e    6
f    2
g    9
dtype: int64


In [ ]:
data = {
"calories": [420, 380, 390],
"duration": [50, 40, 45]
}
df = pd.DataFrame(data)
print(df)
print(df.loc[0])
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [ ]:
df = pd.read_csv('appleAppData.csv')
# print(df.to_string())

In [ ]:
df.head()

App_Id                 App_Name  \
0               com.hkbu.arc.apaper           A+ Paper Guide   
1               com.dmitriev.abooks                  A-Books   
2                    no.terp.abooks                  A-books   
3          fr.antoinettefleur.Book1              A-F Book #1   
4  com.imonstersoft.azdictionaryios  A-Z Synonyms Dictionary   

                                        AppStore_Url Primary_Genre  \
0  https://apps.apple.com/us/app/a-paper-guide/id...     Education   
1  https://apps.apple.com/us/app/a-books/id103157...          Book   
2  https://apps.apple.com/us/app/a-books/id145702...          Book   
3  https://apps.apple.com/us/app/a-f-book-1/id500...          Book   
4  https://apps.apple.com/us/app/a-z-synonyms-dic...     Reference   

  Content_Rating  Size_Bytes Required_IOS_Version              Released  \
0             4+    21993472                  8.0  2017-09-28T03:02:41Z   
1             4+    13135872                 10.0  2015-08-31T19:31:32Z   
2             4+    21943296                  9.0  2021-04-14T07:00:00Z   
3             4+    81851392                  8.0  2012-02-10T03:40:07Z   
4             4+    64692224                  9.0  2020-12-16T08:00:00Z   

                Updated Version  ...  Currency   Free   DeveloperId  \
0  2018-12-21T21:30:36Z   1.1.2  ...       USD   True  1.375411e+09   
1  2019-07-23T20:31:09Z     1.3  ...       USD   True  1.031572e+09   
2  2021-05-30T21:08:54Z   1.3.1  ...       USD   True  1.457024e+09   
3  2019-10-29T12:40:37Z     1.2  ...       USD  False  4.395688e+08   
4  2020-12-18T21:36:11Z   1.0.1  ...       USD   True  6.567318e+08   

        Developer                                      Developer_Url  \
0        HKBU ARC  https://apps.apple.com/us/developer/hkbu-arc/i...   
1  Roman Dmitriev  https://apps.apple.com/us/developer/roman-dmit...   
2         Terp AS  https://apps.apple.com/us/developer/terp-as/id...   
3   i-editeur.com  https://apps.apple.com/us/developer/i-editeur-...   
4   Ngov chiheang  https://apps.apple.com/us/developer/ngov-chihe...   

         Developer_Website Average_User_Rating  Reviews  \
0                      NaN                 0.0      0.0   
1                      NaN                 5.0      1.0   
2                      NaN                 0.0      0.0   
3                      NaN                 0.0      0.0   
4  http://imonstersoft.com                 0.0      0.0   

   Current_Version_Score  Current_Version_Reviews  
0                    0.0                      0.0  
1                    5.0                      1.0  
2                    0.0                      0.0  
3                    0.0                      0.0  
4                    0.0                      0.0  

[5 rows x 21 columns]

In [ ]:
print(df)

                                     App_Id                 App_Name  \
0                       com.hkbu.arc.apaper           A+ Paper Guide   
1                       com.dmitriev.abooks                  A-Books   
2                            no.terp.abooks                  A-books   
3                  fr.antoinettefleur.Book1              A-F Book #1   
4          com.imonstersoft.azdictionaryios  A-Z Synonyms Dictionary   
...                                     ...                      ...   
22124                     com.rrms.raillinq                Rail LinQ   
22125                  com.bauermedia.fv.rl                Rail Live   
22126  com.maharajaassociates.SliderExample         Rail Suraksha tp   
22127                    com.railtasker.app              Rail Tasker   
22128                   ru.ctm.rail-locator             Rail-Локатор   

                                            AppStore_Url Primary_Genre  \
0      https://apps.apple.com/us/app/a-paper-guide/id...     

In [ ]:
print(pd.options.display.max_rows)

60


In [ ]:
pd.options.display.max_rows = 9999

In [ ]:
print(df.head(10))

                             App_Id  \
0               com.hkbu.arc.apaper   
1               com.dmitriev.abooks   
2                    no.terp.abooks   
3          fr.antoinettefleur.Book1   
4  com.imonstersoft.azdictionaryios   
5                   com.sm.apjkalam   
6    com.chawlapublication.andhralr   
7  BestPracticeSystems.IOSAppUpload   
8                    a2.it.team.leo   
9                   com.aaaakh.news   

                                            App_Name  \
0                                     A+ Paper Guide   
1                                            A-Books   
2                                            A-books   
3                                        A-F Book #1   
4                            A-Z Synonyms Dictionary   
5  A. P. J. Abdul Kalam Quotes olx Quotation Flip...   
6                       A.P. Telangana Legal Reports   
7                             A19BestPracticeSystems   
8                                       A2 Directory   
9         

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22129 entries, 0 to 22128
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   App_Id                   22129 non-null  object 
 1   App_Name                 22129 non-null  object 
 2   AppStore_Url             22129 non-null  object 
 3   Primary_Genre            22129 non-null  object 
 4   Content_Rating           22129 non-null  object 
 5   Size_Bytes               22129 non-null  int64  
 6   Required_IOS_Version     22129 non-null  object 
 7   Released                 22129 non-null  object 
 8   Updated                  22128 non-null  object 
 9   Version                  22128 non-null  object 
 10  Price                    22128 non-null  float64
 11  Currency                 22128 non-null  object 
 12  Free                     22128 non-null  object 
 13  DeveloperId              22128 non-null  float64
 14  Developer             

In [ ]:
print(df.tail())

                                     App_Id          App_Name  \
22124                     com.rrms.raillinq         Rail LinQ   
22125                  com.bauermedia.fv.rl         Rail Live   
22126  com.maharajaassociates.SliderExample  Rail Suraksha tp   
22127                    com.railtasker.app       Rail Tasker   
22128                   ru.ctm.rail-locator      Rail-Локатор   

                                            AppStore_Url Primary_Genre  \
22124  https://apps.apple.com/us/app/rail-linq/id1452...      Business   
22125  https://apps.apple.com/us/app/rail-live/id1565...      Business   
22126  https://apps.apple.com/us/app/rail-suraksha-tp...      Business   
22127  https://apps.apple.com/us/app/rail-tasker/id14...      Business   
22128  https://apps.apple.com/us/app/rail-%D0%BB%D0%B...      Business   

      Content_Rating  Size_Bytes Required_IOS_Version              Released  \
22124             4+    78453760                 12.0  2019-07-30T07:00:00Z   
22125 

In [ ]:
new_df = df.dropna()

In [ ]:
new_df.head()

App_Id                        App_Name  \
4   com.imonstersoft.azdictionaryios         A-Z Synonyms Dictionary   
7   BestPracticeSystems.IOSAppUpload          A19BestPracticeSystems   
9                    com.aaaakh.news                         A4 News   
11        com.goodbarber.bigbookfree        AA Big Book (Unofficial)   
13            com.aabigbook.appstore  AA Big Book App  -  Unofficial   

                                         AppStore_Url Primary_Genre  \
4   https://apps.apple.com/us/app/a-z-synonyms-dic...     Reference   
7   https://apps.apple.com/us/app/a19bestpractices...          Book   
9   https://apps.apple.com/us/app/a4-news/id145538...          News   
11  https://apps.apple.com/us/app/aa-big-book-unof...          Book   
13  https://apps.apple.com/us/app/aa-big-book-app-...          Book   

   Content_Rating  Size_Bytes Required_IOS_Version              Released  \
4              4+    64692224                  9.0  2020-12-16T08:00:00Z   
7              4+    15737856                 12.0  2020-10-17T07:00:00Z   
9              4+    13825024                 13.0  2019-05-24T14:20:55Z   
11            17+    63112192                  9.0  2015-05-12T07:45:22Z   
13            17+     2094080                  8.0  2015-12-19T00:41:11Z   

                 Updated Version  ...  Currency   Free   DeveloperId  \
4   2020-12-18T21:36:11Z   1.0.1  ...       USD   True  6.567318e+08   
7   2020-10-19T18:55:40Z     2.1  ...       USD   True  1.535421e+09   
9   2020-09-29T15:28:14Z     2.0  ...       USD   True  5.868675e+08   
11  2021-09-18T18:55:21Z  2.2.16  ...       USD   True  1.473748e+09   
13  2018-10-17T20:01:47Z   1.4.2  ...       USD  False  2.957757e+08   

            Developer                                      Developer_Url  \
4       Ngov chiheang  https://apps.apple.com/us/developer/ngov-chihe...   
7        Gregor Anton  https://apps.apple.com/us/developer/gregor-ant...   
9       Pich Prathana  https://apps.apple.com/us/developer/pich-prath...   
11  Sobriety Soft LLC  https://apps.apple.com/us/developer/sobriety-s...   
13          Dean Huff  https://apps.apple.com/us/developer/dean-huff/...   

                                    Developer_Website Average_User_Rating  \
4                             http://imonstersoft.com             0.00000   
7   https://bestpractice.systems/about-ios-mobile-...             0.00000   
9                             https://www.softive.com             0.00000   
11                            http://sobrietysoft.org             4.78902   
13                            http://aabigbookapp.com             3.09524   

    Reviews  Current_Version_Score  Current_Version_Reviews  
4       0.0                0.00000                      0.0  
7       0.0                0.00000                      0.0  
9       0.0                0.00000                      0.0  
11   1839.0                4.78902                   1839.0  
13     21.0                3.09524                     21.0  

[5 rows x 21 columns]

In [ ]:
print(new_df.to_string())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
df.dropna(inplace=True)

In [ ]:
print(df.head())

                              App_Id                        App_Name  \
4   com.imonstersoft.azdictionaryios         A-Z Synonyms Dictionary   
7   BestPracticeSystems.IOSAppUpload          A19BestPracticeSystems   
9                    com.aaaakh.news                         A4 News   
11        com.goodbarber.bigbookfree        AA Big Book (Unofficial)   
13            com.aabigbook.appstore  AA Big Book App  -  Unofficial   

                                         AppStore_Url Primary_Genre  \
4   https://apps.apple.com/us/app/a-z-synonyms-dic...     Reference   
7   https://apps.apple.com/us/app/a19bestpractices...          Book   
9   https://apps.apple.com/us/app/a4-news/id145538...          News   
11  https://apps.apple.com/us/app/aa-big-book-unof...          Book   
13  https://apps.apple.com/us/app/aa-big-book-app-...          Book   

   Content_Rating  Size_Bytes Required_IOS_Version              Released  \
4              4+    64692224                  9.0  2020-12-16T0

In [ ]:
df["Reviews"].fillna(3,inplace=True)

In [ ]:
Data = [[2,3,4],
        [5,6,7]]
sdata = pd.Series(Data)
print(sdata)

0    [2, 3, 4]
1    [5, 6, 7]
dtype: object


In [ ]:
lst = [['Data', 3], ['Analytics', 36],
['Python', 6], ['R', 9]]
df1 = pd.DataFrame(lst, columns =['Tag', 'number'])
print(df1)

         Tag  number
0       Data       3
1  Analytics      36
2     Python       6
3          R       9


In [ ]:
lst1 = [['tom', 'reacher', 25], ['krish', 'pete', 30],
['nick', 'wilson', 26], ['juli', 'williams', 22]]
df2 = pd.DataFrame(lst1, columns =['FName', 'LName', 'Age'],
dtype = float)
print(df2)

   FName     LName   Age
0    tom   reacher  25.0
1  krish      pete  30.0
2   nick    wilson  26.0
3   juli  williams  22.0


<ipython-input-47-69744263768a>:3: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df2 = pd.DataFrame(lst1, columns =['FName', 'LName', 'Age'],


In [ ]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits)

In [ ]:
print(S+S2)
print("Sum of S: ",sum(S))

apples      37
oranges     46
cherries    83
pears       42
dtype: int64
Sum of S:  115


In [ ]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
fruits_tr = ['elma', 'portakal', 'kiraz', 'armut']
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits_tr)
print(S + S2)

apples     NaN
armut      NaN
cherries   NaN
elma       NaN
kiraz      NaN
oranges    NaN
pears      NaN
portakal   NaN
dtype: float64


In [ ]:
fruits = ['peaches', 'oranges', 'cherries', 'pears']
fruits2 = ['raspberries', 'oranges', 'cherries', 'pears']
S = pd.Series([20, 33, 52, 10], index=fruits, dtype=int)
S2 = pd.Series([17, 13, 31, 32], index=fruits2, dtype=int)

In [ ]:
s = pd.Series([S,S2],dtype="int").sum()

In [ ]:
print(s)

(20, 33, 52, 10, 17, 13, 31, 32)


In [ ]:
print(S+S2)

cherries       83.0
oranges        46.0
peaches         NaN
pears          42.0
raspberries     NaN
dtype: float64


In [ ]:
fruits = ['apples', 'oranges', 'cherries', 'pears']
fruits_tr = ['elma', 'portakal', 'kiraz', 'armut']
S = pd.Series([20, 33, 52, 10], index=fruits)
S2 = pd.Series([17, 13, 31, 32], index=fruits_tr)
print(S + S2)

apples     NaN
armut      NaN
cherries   NaN
elma       NaN
kiraz      NaN
oranges    NaN
pears      NaN
portakal   NaN
dtype: float64


In [ ]:
print(S['apples'])

20


In [ ]:
S.apply(np.log)

apples      2.995732
oranges     3.496508
cherries    3.951244
pears       2.302585
dtype: float64

In [ ]:
S.apply(lambda x: x if x>50 else x+10)

apples      30
oranges     43
cherries    52
pears       20
dtype: int64

In [ ]:
S[S>30]

oranges     33
cherries    52
dtype: int64

In [ ]:
"cherries" in S

True

In [ ]:
cities = {"London": 8615246,
          "Berlin": 3562166,
          "Madrid": 3165235,
          "Rome": 2874038,
          "Paris": 2273305,
          "Vienna": 1805681,
          "Bucharest": 1803425,
          "Hamburg": 1760433,
          "Budapest": 1754000,
          "Warsaw": 1740119,
          "Barcelona": 1602386,
          "Munich": 1493900,
          "Milan": 1350680
          }
city_series = pd.Series(cities)
print(city_series)

London       8615246
Berlin       3562166
Madrid       3165235
Rome         2874038
Paris        2273305
Vienna       1805681
Bucharest    1803425
Hamburg      1760433
Budapest     1754000
Warsaw       1740119
Barcelona    1602386
Munich       1493900
Milan        1350680
dtype: int64


In [ ]:
my_cities = ["London", "Paris", "Zurich", "Berlin",
"Stuttgart", "Hamburg"]
my_city_series = pd.Series(cities, index=my_cities, dtype=int)

In [ ]:
print(my_city_series)
new_city_series = my_city_series.fillna(300)

London       8615246.0
Paris        2273305.0
Zurich           300.0
Berlin       3562166.0
Stuttgart        300.0
Hamburg      1760433.0
dtype: float64


In [ ]:
my_cities = ["London", "Paris", "Berlin", "Hamburg"]
my_city_series = pd.Series(cities,
index=my_cities)
print(my_city_series)

London     8615246
Paris      2273305
Berlin     3562166
Hamburg    1760433
dtype: int64


In [ ]:
print(my_city_series.isnull())

London     False
Paris      False
Berlin     False
Hamburg    False
dtype: bool


In [ ]:
print(my_city_series.notnull())

London     True
Paris      True
Berlin     True
Hamburg    True
dtype: bool


In [ ]:
lst = [['Data',25],['Analysis',30],['Python',26]]
df3 = pd.DataFrame(lst, columns=['Tag','Number'],index=['1','2','3'])

In [ ]:
print(df3)

        Tag  Number
1      Data      25
2  Analysis      30
3    Python      26


In [ ]:
data1 = {'Category':['Array','Stack','Queue'],
         'Marks':[20,21,19]}
df4 = pd.DataFrame(data1)

In [ ]:
print(df4)

  Category  Marks
0    Array     20
1    Stack     21
2    Queue     19


In [ ]:
dict1 = {'name':["reyansh", "hitz", "khushi", "Sisa"],
'degree': ["MBA", "BCA", "M.Tech", "MBA"],
'score':[90, 40, 80, 98]}
df = pd.DataFrame(dict1)
print(df)

      name  degree  score
0  reyansh     MBA     90
1     hitz     BCA     40
2   khushi  M.Tech     80
3     Sisa     MBA     98


In [ ]:
for i,j in df.iterrows():
  print(i,j)

0 name      reyansh
degree        MBA
score          90
Name: 0, dtype: object
1 name      hitz
degree     BCA
score       40
Name: 1, dtype: object
2 name      khushi
degree    M.Tech
score         80
Name: 2, dtype: object
3 name      Sisa
degree     MBA
score       98
Name: 3, dtype: object


In [ ]:
columns = list(df)
for i in columns:
  print(df[i][2])

khushi
M.Tech
80


In [ ]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df1 = pd.DataFrame(data)

In [ ]:
df1["Name"] = df1["Name"].str.lower()

In [ ]:
print(df1)

     Name  Age    Address Qualification
0     jai   27      Delhi           Msc
1  princi   24     Kanpur            MA
2  gaurav   22  Allahabad           MCA
3    anuj   32    Kannauj           Phd


In [ ]:
print(df1.to_numpy())

[['jai' 27 'Delhi' 'Msc']
 ['princi' 24 'Kanpur' 'MA']
 ['gaurav' 22 'Allahabad' 'MCA']
 ['anuj' 32 'Kannauj' 'Phd']]


In [ ]:
data = {"Product_Name":["Keyboard","Mouse", "Monitor", "CPU","CPU", "Speakers","Headset"],
        "Unit_Price":[500,200, 5000.235, 10000.550, 10000.550, 250.50,None],
        "No_Of_Units":[5,5, 10, 20, 20, 8,pd.NaT],
        "Available_Quantity":[5,6,10,"Not Available","Not Available", pd.NaT,pd.NaT],
        "Available_Since_Date":['11/5/2021', '4/23/2021', '08/21/2021','09/18/2021','09/18/2021','01/05/2021',pd.NaT],
        "Remarks":[pd.NaT,pd.NaT,pd.NaT,pd.NaT,pd.NaT,pd.NaT,pd.NaT]
        }
df = pd.DataFrame(data)
df = df.astype({"Unit_Price": float})
print(df)

  Product_Name  Unit_Price No_Of_Units Available_Quantity  \
0     Keyboard     500.000           5                  5   
1        Mouse     200.000           5                  6   
2      Monitor    5000.235          10                 10   
3          CPU   10000.550          20      Not Available   
4          CPU   10000.550          20      Not Available   
5     Speakers     250.500           8                NaT   
6      Headset         NaN         NaT                NaT   

  Available_Since_Date Remarks  
0            11/5/2021     NaT  
1            4/23/2021     NaT  
2           08/21/2021     NaT  
3           09/18/2021     NaT  
4           09/18/2021     NaT  
5           01/05/2021     NaT  
6                  NaT     NaT  


In [ ]:
df

Product_Name  Unit_Price No_Of_Units Available_Quantity  \
0     Keyboard     500.000           5                  5   
1        Mouse     200.000           5                  6   
2      Monitor    5000.235          10                 10   
3          CPU   10000.550          20      Not Available   
4          CPU   10000.550          20      Not Available   
5     Speakers     250.500           8                NaT   
6      Headset         NaN         NaT                NaT   

  Available_Since_Date Remarks  
0            11/5/2021     NaT  
1            4/23/2021     NaT  
2           08/21/2021     NaT  
3           09/18/2021     NaT  
4           09/18/2021     NaT  
5           01/05/2021     NaT  
6                  NaT     NaT

In [ ]:
df.iat[1,3]

6

# Numpy

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
arr = np.array([1,2,3])

In [ ]:
print(arr)

[1 2 3]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array(42)

In [ ]:
print(arr1)

42


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9,0]])

<ipython-input-111-bfe671eae504>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[1,2,3],[4,5,6],[7,8,9,0]])


In [ ]:
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9, 0])]
1
(3,)


In [ ]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr3[0:5,3])
print(arr3[1,3:5])

[4 9]
[ 9 10]


In [ ]:
arr4 = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])

In [ ]:
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4
(2, 2, 2, 3)


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
print(arr[0])

1


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [ ]:
arr5 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr5[0, 1])

2nd element on 1st row:  2


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
print(arr[::2])

[1 3 5 7]


In [ ]:
arr6 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr6[0:2,2])

[3 8]
